-- IMEI WEB APP V2 - run once in Supabase SQL Editor
create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

alter table public.dubai_scans add column if not exists shipment_id bigint;

do $$ begin
  if not exists (select 1 from pg_constraint where conname='dubai_scans_shipment_id_fkey') then
    alter table public.dubai_scans add constraint dubai_scans_shipment_id_fkey foreign key (shipment_id) references public.shipments(id);
  end if;
end $$;

do $$
declare previous_shipment_id bigint;
begin
  if exists (select 1 from public.dubai_scans where shipment_id is null) then
    insert into public.shipments(name,status,closed_at) values('Previous Dubai Scans','closed',now()) returning id into previous_shipment_id;
    update public.dubai_scans set shipment_id=previous_shipment_id where shipment_id is null;
  end if;
end $$;

alter table public.dubai_scans alter column shipment_id set not null;
alter table public.shipments enable row level security;
alter table public.dubai_scans enable row level security;

drop policy if exists "Allow public read shipments" on public.shipments;
drop policy if exists "Allow public insert shipments" on public.shipments;
drop policy if exists "Allow public update shipments" on public.shipments;
create policy "Allow public read shipments" on public.shipments for select to anon using (true);
create policy "Allow public insert shipments" on public.shipments for insert to anon with check (true);
create policy "Allow public update shipments" on public.shipments for update to anon using (true) with check (true);

drop policy if exists "Allow public read of dubai scans" on public.dubai_scans;
drop policy if exists "Allow public insert of dubai scans" on public.dubai_scans;
drop policy if exists "Allow public delete dubai scans" on public.dubai_scans;
create policy "Allow public read of dubai scans" on public.dubai_scans for select to anon using (true);
create policy "Allow public insert of dubai scans" on public.dubai_scans for insert to anon with check (true);
create policy "Allow public delete dubai scans" on public.dubai_scans for delete to anon using (true);

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='shipments') then
    alter publication supabase_realtime add table public.shipments;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='dubai_scans') then
    alter publication supabase_realtime add table public.dubai_scans;
  end if;
end $$;
