-- ============================================================
-- IMEI WEB APP - FULL SUPABASE SETUP / REPAIR
-- Use this instead of the previous upgrade file.
-- Safe for a fresh project and also handles an existing dubai_scans table.
-- ============================================================

-- 1) Shipments table
create table if not exists public.shipments (
    id bigint generated by default as identity primary key,
    name text not null,
    status text not null default 'open'
        check (status in ('open','closed')),
    created_at timestamptz not null default now(),
    closed_at timestamptz
);

-- 2) Dubai scans table
create table if not exists public.dubai_scans (
    imei text primary key,
    created_at timestamptz not null default now(),
    shipment_id bigint
);

-- 3) Make sure shipment_id exists if dubai_scans was an older table
alter table public.dubai_scans
add column if not exists shipment_id bigint;

-- 4) Add foreign key if missing
do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'dubai_scans_shipment_id_fkey'
    ) then
        alter table public.dubai_scans
        add constraint dubai_scans_shipment_id_fkey
        foreign key (shipment_id)
        references public.shipments(id);
    end if;
end $$;

-- 5) If older scans exist without a shipment, move them into one closed shipment
do $$
declare
    previous_shipment_id bigint;
begin
    if exists (
        select 1
        from public.dubai_scans
        where shipment_id is null
    ) then

        insert into public.shipments (
            name,
            status,
            closed_at
        )
        values (
            'Previous Dubai Scans',
            'closed',
            now()
        )
        returning id into previous_shipment_id;

        update public.dubai_scans
        set shipment_id = previous_shipment_id
        where shipment_id is null;
    end if;
end $$;

-- 6) New scans must belong to a shipment
alter table public.dubai_scans
alter column shipment_id set not null;

-- 7) Enable RLS
alter table public.shipments enable row level security;
alter table public.dubai_scans enable row level security;

-- 8) Shipment policies
drop policy if exists "Allow public read shipments"
on public.shipments;

drop policy if exists "Allow public insert shipments"
on public.shipments;

drop policy if exists "Allow public update shipments"
on public.shipments;

create policy "Allow public read shipments"
on public.shipments
for select
to anon
using (true);

create policy "Allow public insert shipments"
on public.shipments
for insert
to anon
with check (true);

create policy "Allow public update shipments"
on public.shipments
for update
to anon
using (true)
with check (true);

-- 9) Dubai scan policies
drop policy if exists "Allow public read of dubai scans"
on public.dubai_scans;

drop policy if exists "Allow public insert of dubai scans"
on public.dubai_scans;

drop policy if exists "Allow public delete dubai scans"
on public.dubai_scans;

create policy "Allow public read of dubai scans"
on public.dubai_scans
for select
to anon
using (true);

create policy "Allow public insert of dubai scans"
on public.dubai_scans
for insert
to anon
with check (true);

create policy "Allow public delete dubai scans"
on public.dubai_scans
for delete
to anon
using (true);

-- 10) Explicit API grants
grant select, insert, update on public.shipments to anon, authenticated;
grant select, insert, delete on public.dubai_scans to anon, authenticated;

-- Identity sequence used when creating a shipment
grant usage, select on sequence public.shipments_id_seq to anon, authenticated;

-- 11) Realtime for shipments
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'shipments'
    ) then
        alter publication supabase_realtime
        add table public.shipments;
    end if;
end $$;

-- 12) Realtime for dubai_scans
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'dubai_scans'
    ) then
        alter publication supabase_realtime
        add table public.dubai_scans;
    end if;
end $$;
